### PR TITLE
ROS 2 uses same rosdistro URL as ROS 1

### PR DESCRIPTION
**Pull request by sloretz**
I mistakenly merged #224, forgetting that file is generated

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Can the line be removed completely if it's now using the default url?

**Comment by ruffsl** [comment]
> Can the line be removed completely if it's now using the default url?

Yep, that what ros released ros2 images for the library do as well

**Comment by sloretz** [comment]
> Can the line be removed completely if it's now using the default url?

I'm not sure. After removing `rosdistro_index_url` and running `./create_dockerfiles.py dir -d ./source/` it looks like the `bootstrap rosdep` section is gone from the dockerfile. @ruffsl is anything else initializing rosdep? Does rosdep need to be initialized for this dockerfile?


```
diff --git a/ros2/source/images.yaml.em b/ros2/source/images.yaml.em
index def2dac..81b1da6 100644
--- a/ros2/source/images.yaml.em
+++ b/ros2/source/images.yaml.em
@@ -39,7 +39,6 @@ images:
                 -DSECURITY=ON --no-warn-unused-cli
             - --symlink-install
         rosdep:
-            rosdistro_index_url: https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml
             install:
                 - --from-paths src
                 - --ignore-src
diff --git a/ros2/source/source/Dockerfile b/ros2/source/source/Dockerfile
index b761a3d..d22d475 100644
--- a/ros2/source/source/Dockerfile
+++ b/ros2/source/source/Dockerfile
@@ -53,10 +53,6 @@ RUN pip3 install -U \
     pytest-repeat \
     pytest-rerunfailures
 
-# bootstrap rosdep
-ENV ROSDISTRO_INDEX_URL https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml
-RUN rosdep init \
-    && rosdep update
 
 # clone source
 ENV ROS2_WS /root/ros2_ws
```

**Comment by mikaelarguedas** [comment]
The source image template will need to be updated accordingly:
https://github.com/osrf/docker_templates/blob/db5ac1415b9c6c3fd0c26a6160b6e52a10bcc367/docker_templates/templates/docker_images_ros2/source/create_ros_image.Dockerfile.em#L79

**Comment by sloretz** [comment]
> The source image template will need to be updated accordingly:

I see. Something like osrf/docker_templates#50 ?

**Comment by ruffsl** [comment]
Yea, the template and the source dockerfiles are a little out of sync (the CI isn't yet auto generating them). I intended to come back and refactor them a little to bring them back into step after the nightly image template PR https://github.com/osrf/docker_templates/pull/49 , but got sidetracked.

**Pull request closed without merging**
