### PR TITLE
Add Melodic dockerfiles

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Note: I didnt add artful as it's almost EOL, so this adds only Debian Stretch and Ubuntu Bionic.

Depending on the final state of https://github.com/osrf/docker_templates/pull/34 this PR may require changes before being merged and released.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
This PR has been updated to integrate the changes from https://github.com/osrf/docker_templates/pull/34
Travis is happy.
I built all the images locally and ran a basic talker listener example, they seem to work fine.
I think this is ready for review

**Comment by mikaelarguedas** [comment]
alright merging then. Thank you both for the review

**Comment by ruffsl** [comment]
@mikaelarguedas , just curious, why is the core meta package so large now for melodic?
``` shell
$ docker images
REPOSITORY                         TAG                             IMAGE ID            CREATED              SIZE
ros                                melodic-robot-stretch           76f283e121eb        About a minute ago   1.53GB
ros                                melodic-ros-base-stretch        07cfc2296663        About a minute ago   1.36GB
ros                                melodic-ros-core-stretch        2a5fa70f7c7b        2 minutes ago        1.05GB
ros                                melodic-ros-core-bionic         ec235807c793        5 minutes ago        954MB

```

For comparison:
kinetic-ros-core-jessie 291 MB
lunar-ros-core-stretch 370 MB
lunar-ros-core-xenial 298 MB
lunar-ros-core 298 MB

**Comment by mikaelarguedas** [comment]
Oh interesting, thanks for catching that.
I don't know where the size bump comes from :S I'll have a look

**Comment by mikaelarguedas** [comment]
hmmm that's surprising, if I start from a bare stretch and install only ros-core for lunar and melodic they are supposed to end up with roughly the same size...
Stretch/lunar:
```
# apt-get install ros-lunar-ros-core
...
0 upgraded, 342 newly installed, 0 to remove and 0 not upgraded.
Need to get 200 MB of archives.
After this operation, 831 MB of additional disk space will be used.
```
Stretch/melodic:
```
# apt-get install ros-melodic-ros-core
...
0 upgraded, 343 newly installed, 0 to remove and 0 not upgraded.
Need to get 200 MB of archives.
After this operation, 831 MB of additional disk space will be used.
```

**Comment by mikaelarguedas** [comment]
Building them locally (lunar-ros-core-stretch and melodic-ros-core-stretch) they both result in a 1.05GB image. Not sure why the size is much smaller in the images hosted on dockerhub

**Comment by mikaelarguedas** [comment]
@davetcoleman @vooon  FYI

**Comment by davetcoleman** [comment]
Thanks! I'll switch over moveit soon!

**Comment by mikaelarguedas** [comment]
> Thanks! I'll switch over moveit soon!

:+1: 
It may take a couple days before the images are merged and built on dockerhub: https://github.com/docker-library/official-images/pull/4356

**Comment by tfoote** [comment]
@ruffsl Are those comaring the same things? I think the dockerhub numbers are the size of the images in their compressed/serialized layers. Whereas the local display is the resultant disk usage of all the layers combined. 

```
ros                                          lunar-ros-base-xenial       133ce87ed3ae        9 months ago        952MB
```

**Comment by ruffsl** [comment]
@tfoote Hmm, I looked into it and it seem your right,
but it also looks like I'm not the first one bamboozled:
[Official image sizes in Docker Hub are 3x off #331](https://github.com/docker/hub-feedback/issues/331)

I've been always keeping tabs on image size through our microbadger stats,
but this seems a little fraudulent given dockerhubs reported metrics:
https://microbadger.com/images/library/ros

**Pull request merged**
