### PR TITLE
Work around rviz_common import error

### PR DESCRIPTION
**Pull request by ruffsl**
Related:
https://github.com/ament/ament_cmake/issues/173
https://github.com/ros-planning/navigation2/issues/799
https://github.com/ros-planning/navigation2/pull/806

Ping @crdelsey

### CODE REVIEW

**Comment by crdelsey** [comment]
Thanks. I'll hold off on merging my workaround since you got this done so fast.

**Comment by ruffsl** [comment]
@osrf/docker-image-maintainers , feel free to merge if approved.

**Comment by mikaelarguedas** [comment]
Yeah that's one way to work around it.

I don't see a working case before that would be broken by this change and as it seems to fix navigation2 ci that's fine by me as a temporary workaround :+1: .

From the issue description it sounds like the issue is assumed to be in the nightly image, but at first glance it looks like any user using the extracted archive as an underlay will be facing the same problem (docker involved or not), is that correct?

@crdelsey Will the end issue and long term fix be located on the ros2/rviz repository ?

**Comment by crdelsey** [comment]
> any user using the extracted archive as an underlay will be facing the same problem (docker involved or not), is that correct

Yes that is correct.

> Will the end issue and long term fix be located on the ros2/rviz repository ?

I don't know. I don't think so.  I don't understand the correct solution yet. There are 3 possibilities I can see:
1. Fix ament. Since CMake doesn't seem to support what we need here, it probably means making a custom equivalent of what CMake does internally.
2. Change the rviz build to not use interfaces. I'm not sure they are really necessary in this case, but there are other packages that use them as well, so they'd still have the problem
3. Change the way the build farm does the nightly build, so that the packages end up in the /opt/ros/... directory tree.

**Comment by mikaelarguedas** [comment]
thanks @crdelsey for the clarification :+1:

**Pull request merged**
