### PR TITLE
Add arm32v7 to dashing

### PR DESCRIPTION
**Pull request by ruffsl**
Completes https://github.com/osrf/docker_images/pull/325

### CODE REVIEW

**Comment by ruffsl** [comment]
I acknowledge that armhf it's not a tier1 supported platform, but given its tier2 for both dashing and eloquent, I'm not sure why they should be treated differently for exploratory test builds? Dashing is still the latest LTS, so more users on devices like Raspberry pies are likely to test dashing armhf images.

**Comment by mikaelarguedas** [comment]
Maybe this should stay on the previous ticket where the discussion happened originally to avoid scattering information and keep original reviewers in the loop

**Comment by ruffsl** [comment]
The original or commiter hasn't completed the unfinished PR for 2 months, so it was closed and finished here. Feel free to continue the discussion on the active PR. Ping @nuclearsandwich

**Comment by piraka9011** [comment]
Dashing is the first LTS release for ROS2 and I think having a Docker image for it is a demonstration of the community's commitment to supporting different robot platforms. Especially new folks tinkering with their Turtlebot/Pi's and what not.

Our team (AWS) also has a use case for `arm32v7` Docker since it makes it easier to test our contributions locally so I am in favor of adding `arm32v7` support. We've been [monitoring the armhf builds](https://github.com/ros-security/aws-oncall) and have been working towards keeping the builds green.

**Comment by nuclearsandwich** [comment]
I'm not the one doing any extra work to support these Docker images so I am not putting my foot down against armhf images.

**Comment by ruffsl** [comment]
I light of the multiple requests from the community, I'll merge this and keep a close eye for `arm32v7` image related issues.

**Pull request merged**
