### PR TITLE
Foxy images

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Opening for visibility, this is on hold until the beta releases of Noetic and Foxy are out. From there we'll need to generate the dockerfiles associated to this manifest change

Note: this point the `ros:latest` tag to Foxy according to https://github.com/osrf/docker_images/issues/286. Documentation will need to be updated accordingly

Edit: Noetic images have been released in a separate PR https://github.com/osrf/docker_images/pull/405

### CODE REVIEW

**Comment by sloretz** [comment]
@mikaelarguedas @ruffsl friendly ping. All Noetic packages up to `ros-noetic-desktop-full` are in the testing repo for amd64 as well as all packages up to `ros-noetic-desktop` for arm64 (Focal and Buster) + armhf (Focal only). I'll sync to main tomorrow morning PDT before announcing Noetic's release at noon-ish.

I think [Foxy's release date is June 5th](https://index.ros.org/doc/ros2/Releases/Release-Foxy-Fitzroy/).

I'm not exactly sure what that means for this PR. It takes me a little while to study this repo when coming back to it. Anything needed from me for these Docker images?

**Comment by ruffsl** [comment]
Yea, I was about to comment to suggest splitting this PR into two given the time between the distro releases. That way we could merge as soon as the first is ready. The docker library admins may not see our upstream PR until Monday though.

**Comment by mikaelarguedas** [comment]
Noetic is now its own standalone PR https://github.com/osrf/docker_images/pull/405

Needs some tweaks to the snippets before resulting in building Dockerfiles, more details on the PR.

This PR has been updated to be Foxy only. It requires noetic to be released first and does not provide images for arm32 as it seems that it may not get foxy binaries.

**Comment by ruffsl** [comment]
@mikaelarguedas , looks like the generated files are now building from the release repo, see latest push onto PR. Are there any other blockers?

**Comment by mikaelarguedas** [comment]
Nope this was just waiting for a sync and [an announcement](https://discourse.ros.org/t/ros-foxy-fitzroy-released/14495) !

**Pull request merged**
