### PR TITLE
Initial attempt at bouncy source install Dockerfile

### PR DESCRIPTION
**Pull request by calvertdw**
by copying the source/source and replacing distro name with bouncy.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
> Currently building the ros1_bridge is necessary to use custom messages, and furthermore, it is necessary to have a source ros2 installation built before building the bridge.

This shouldn't be necessary, building the bridge on top of the debs should be possible. If it doesn't it's a bug. Users should not have to build all ROS 2 from source just to be able to build a custom bridge.

You should be able to:
- install all the packages you need from deb (or work from one of the released docker images)
- create a ros 2 overlay workspace with your custom messages and the bridge
- build all but the bridge: `colcon build --symlink-install --packages-skip ros1_bridge`
- create a ros 1 overlay workspace with your custom messages and build them

Then build the bridge following this section from the `ros1_bridge` README
```
# You have already sourced your ROS installation.
# Source your ROS 2 installation:
. <install-space-with-ros2>/local_setup.bash
# And if you have a ROS 1 overlay workspace, something like:
# . <install-space-to-ros1-overlay-ws>/setup.bash
# And if you have a ROS 2 overlay workspace, something like:
# . <install-space-to-ros2-overlay-ws>/local_setup.bash
colcon build --symlink-install --packages-select ros1_bridge --cmake-force-configure
```

Here `<install-space-with-ros2>` will be `/opt/ros/bouncy`

**Comment by calvertdw** [comment]
Well if anyone was wondering, the image in this PR builds fine.

**Comment by calvertdw** [comment]
@mikaelarguedas When I build my ROS2 ws from the `bouncy-ros1-bridge` image, it, first of all, can't find `colcon`, and if I install `colcon-common-extensions` (and `vcstool`), the build cannot find the package `ament_cmake`.

```
Step 12/12 : RUN colcon build --symlink-install --packages-skip ros1_bridge
 ---> Running in 71a114146ddf
Starting >>> controller_msgs
--- stderr: controller_msgs
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "Findament_cmake.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ament_cmake", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cmake" with
  any of the following names:

    ament_cmakeConfig.cmake
    ament_cmake-config.cmake

  Add the installation prefix of "ament_cmake" to CMAKE_PREFIX_PATH or set
  "ament_cmake_DIR" to a directory containing one of the above files.  If
  "ament_cmake" provides a separate development package or SDK, be sure it
  has been installed.


---
Failed   <<< controller_msgs    [ Exited with code 1 ]
```

Here is my dockerfile:
```
FROM osrf/ros2:bouncy-ros1-bridge

RUN apt-get update
RUN apt-get install -y curl git
RUN pip3 install vcstool colcon-common-extensions

RUN /bin/bash -c "source /opt/ros/$ROS2_DISTRO/setup.bash"

RUN mkdir -p /root/ihmc_ros1_bridge/src

WORKDIR /root/ihmc_ros1_bridge

# Add controller_msgs
COPY src/main/messages/ihmc_interfaces/controller_msgs src/controller_msgs

# Add ihmc_demo_py
COPY src/ihmc_demo_py src/ihmc_demo_py

# Clone ros1_bridge
#   ros2/ros1_bridge:
#    type: git
#    url: https://github.com/ros2/ros1_bridge.git
#    version: 0.5.0
COPY src/rosdocker/linux/ihmc_ros1_bridge.repos .
RUN vcs import src < ihmc_ros1_bridge.repos

RUN colcon build --symlink-install --packages-skip ros1_bridge
```

The controller_msgs package:
https://github.com/ihmcrobotics/ihmc-open-robotics-software/tree/feature/bouncy-windows-and-linux-support/ihmc-interfaces/src/main/messages/ihmc_interfaces/controller_msgs

**Comment by mikaelarguedas** [comment]
> Well if anyone was wondering, the image in this PR builds fine.

Good to know!

>  the build cannot find the package ament_cmake.

You need to source the underlay in the same run command as invoking the build because the environment setup doesn't persist between layers (note that I'm also using the `.sh` version of the setup script).
```
RUN . /opt/ros/bouncy/setup.sh && \
    colcon build --symlink-install --packages-skip ros1_bridge
```

- the apt commands should be in the same layer to have up to date sources when installing and keeping the size minimal (and install the packages from the apt repos rather than pip: 
```
RUN apt-get update && \
    apt-get install -y curl git python3-colcon-common-extensions python3-vcstool && \
    rm -rf /var/lib/apt/lists/*
```

After applying these modifications it works for me:
```
FROM osrf/ros2:bouncy-ros1-bridge

RUN apt-get update && \
    apt-get install -y curl git python3-colcon-common-extensions python3-vcstool && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/ihmc_ros1_bridge/src

WORKDIR /root/ihmc_ros1_bridge

RUN git clone https://github.com/ros2/ros1_bridge.git -b 0.5.0 

COPY ihmc-open-robotics-software/ihmc-interfaces/src/main/messages/ihmc_interfaces/controller_msgs src/controller_msgs
# Clone ros1_bridge
#   ros2/ros1_bridge:
#    type: git
#    url: https://github.com/ros2/ros1_bridge.git
#    version: 0.5.0

RUN . /opt/ros/bouncy/setup.sh && \
    colcon build --symlink-install --packages-skip ros1_bridge --event-handlers console_direct+
```

**Comment by ruffsl** [comment]
Looks like this has been resolved with the proper use of an overlay workspace. Closing PR.

**Pull request closed without merging**
