### PR TITLE
Limit use of release packages on nightly

### PR DESCRIPTION
**Pull request by ruffsl**
By marking all release packages as `hold`
Context: https://github.com/osrf/docker_images/issues/304#issuecomment-520029364

### CODE REVIEW

**Comment by ruffsl** [comment]
Hmm... apt hold seem to prevent apt from updating installed packages, but not installing them in the first place. Might need to use a different method.

**Comment by mikaelarguedas** [comment]
I can open a PR with https://github.com/osrf/docker_templates/commit/9aa7196427e589e6add73ab271b3b2d0b805be87 if you're ok with the approach. Used it successfully earlier today to get the image to fail while listing all the packages and keys that couldn't be resolved

**Comment by ruffsl** [comment]
> but not installing them in the first place.

Check this out:

<details>

```
root@7e5275351444:/# htop
bash: htop: command not found
root@7e5275351444:/# apt update
Get:1 http://packages.ros.org/ros2-testing/ubuntu bionic InRelease [3209 B]
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]                  
Get:4 http://packages.ros.org/ros2-testing/ubuntu bionic/main amd64 Packages [365 kB]        
Get:5 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [597 kB]              
Get:6 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [731 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [5436 B]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [4172 B]                
Get:10 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                          
Get:11 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [14.2 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [906 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1257 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [10.8 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [3930 B]
Get:20 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [2496 B]
Fetched 17.3 MB in 4s (4547 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@7e5275351444:/# apt-mark hold htop
htop set on hold.
root@7e5275351444:/# apt install htop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  lsof strace
The following NEW packages will be installed:
  htop
The following held packages will be changed:
  htop
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 80.0 kB of archives.
After this operation, 221 kB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
```

**Comment by mikaelarguedas** [comment]
After offline discussion with @ruffsl we figured that the inability to install ROS packages via rosdep on nightly images should be a persistent thing. This way consumers of this image will not end up installing most of the last released rosdistro if they have misconfigured dependencies in their workspace.

So we decided to make rosdep fetch an index without any ros distribution. Users will still be able to install ros-$ROS_DISTRO-... packages using apt but rosdep wont be aware of them.

Relevant changes have been force-pushed to this PR and the corresponding template PR is available at https://github.com/osrf/docker_templates/pull/71

**Comment by ruffsl** [comment]
LGTM!

**Pull request merged**
