### PR TITLE
[gazebo] Remove arm archs

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Based on discussion https://github.com/osrf/docker_images/issues/258

### CODE REVIEW

**Comment by ruffsl** [comment]
Will we be notified when the arm builds are updated? I just like to avoid forgetting to revert this, then never having the arm images updated even after the gazebo packages are sync'ed for arm. Though the ci job for that architecture is failing https://doi-janky.infosiftr.net/job/multiarch/job/arm32v7/job/gazebo/ , at least we don't have to do anything on our end, other than just ensure the registry hashes are up to date.

**Comment by mikaelarguedas** [comment]
> I'd just like to avoid forgetting to revert this,

That is a good point
By watching https://bitbucket.org/osrf/gazebo/issues/2691/compilation-problems-for-arm32-and-armhf we will be notified when the status changes.

As these have been failing for a year with no expectation of change in the near future, I'd rather us actively enabling when it is actually supported than consuming hours of build time daily to provide no output or once in a while unsupported content.

In the end, if gazebo doesn't support their releases on arm, I believe we should not do it either.

**Comment by j-rivero** [comment]
> In the end, if gazebo doesn't support their releases on arm, I believe we should not do it either.

I think both of your are right. Makes little sense to support arm docker images until we fix the different bugs affecting the build. To mitigate the problem raised by Ruffin I [dropped a comment ](https://bitbucket.org/osrf/gazebo/issues/2691/compilation-problems-for-arm32-and-armhf#comment-56063781)on the Gazebo issue so we don't forget to come back to this repo once fixed.

**Comment by MaximeAubanel** [comment]
So as of now, there is no way to pull osrf/ros:eloquent-ros1-bridge for arm ?

**Comment by mikaelarguedas** [comment]
> So as of now, there is no way to pull osrf/ros:eloquent-ros1-bridge for arm ?

This is correct, although unrelated to this PR (ros1_bridge and gazebo are independant images) so the fact that gazebo arm compilation problems get resolved won't impact the ros1-bridge images.

Dockerhub doesnt provide ways to compile images for arm on third party profiles (like the osrf one). Only the official docker library has support for that.
So it is not possible to pull *any* images from `osrf/*` for arm.

As ros1_bridge doesn't require any GUI tools, we could submit that image to the official docker library and get arm images built. I opened https://github.com/osrf/docker_images/issues/414 to discuss it

**Pull request merged**
