### PR TITLE
EOL distros need to use snapshots.ros.org

### PR DESCRIPTION
**Pull request by eisoku9618**

### CODE REVIEW

**Comment by ruffsl** [comment]
This doesn't seem to fix the build. Take boxturtle for example:

<details>

```
$ docker build --tag=ros:boxturtle-ros-lucid --no-cache         ros/.
Sending build context to Docker daemon   5.12kB
Step 1/11 : FROM ubuntu:lucid
 ---> e21dbcc7c9de
Step 2/11 : RUN sed -i -e 's/archive/old-releases/g' /etc/apt/sources.list
 ---> Running in 69dbe026d323
Removing intermediate container 69dbe026d323
 ---> 0a846b4f7bd1
Step 3/11 : RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD19BAB3CBF125EA
 ---> Running in 8dd46ce1a553
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /etc/apt/secring.gpg --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD19BAB3CBF125EA
gpg: requesting key CBF125EA from hkp server keyserver.ubuntu.com
gpg: key CBF125EA: public key "ROS Snapshot builder <rosbuild@ros.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Removing intermediate container 8dd46ce1a553
 ---> 7494fe927386
Step 4/11 : RUN echo "deb http://snapshots.ros.org/boxturtle/final/ubuntu lucid main" > /etc/apt/sources.list.d/ros-latest.list
 ---> Running in f5b241ba35fa
Removing intermediate container f5b241ba35fa
 ---> 76b64fbbe554
Step 5/11 : RUN locale-gen en_US.UTF-8
 ---> Running in 87f57a920e21
Generating locales...
  en_US.UTF-8... done
Generation complete.
Removing intermediate container 87f57a920e21
 ---> e67ff4e3707d
Step 6/11 : ENV LANG en_US.UTF-8
 ---> Running in 9dee7ed81c0e
Removing intermediate container 9dee7ed81c0e
 ---> 8e4772ce0745
Step 7/11 : ENV ROS_DISTRO boxturtle
 ---> Running in e6d7bd97c22b
Removing intermediate container e6d7bd97c22b
 ---> dcb9d679cd53
Step 8/11 : RUN apt-get update && apt-get install -y     ros-boxturtle-ros     && rm -rf /var/lib/apt/lists/*     && mkdir /var/lib/apt/lists/partial
 ---> Running in a612c4c270cd
Get:1 http://snapshots.ros.org lucid Release.gpg [630B]
Ign http://snapshots.ros.org/boxturtle/final/ubuntu/ lucid/main Translation-en_US
Get:2 http://snapshots.ros.org lucid Release [11.7kB]
Get:3 http://snapshots.ros.org lucid/main Packages [35.2kB]
Ign http://old-releases.ubuntu.com lucid Release.gpg
Ign http://old-releases.ubuntu.com/ubuntu/ lucid/main Translation-en_US
Ign http://old-releases.ubuntu.com/ubuntu/ lucid/universe Translation-en_US
Ign http://old-releases.ubuntu.com lucid-updates Release.gpg
Ign http://old-releases.ubuntu.com/ubuntu/ lucid-updates/main Translation-en_US
Ign http://old-releases.ubuntu.com/ubuntu/ lucid-updates/universe Translation-en_US
Ign http://old-releases.ubuntu.com lucid-security Release.gpg
Ign http://old-releases.ubuntu.com/ubuntu/ lucid-security/main Translation-en_US
Ign http://old-releases.ubuntu.com/ubuntu/ lucid-security/universe Translation-en_US
Ign http://old-releases.ubuntu.com lucid Release
Ign http://old-releases.ubuntu.com lucid-updates Release
Ign http://old-releases.ubuntu.com lucid-security Release
Ign http://old-releases.ubuntu.com lucid/main Packages
Ign http://old-releases.ubuntu.com lucid/universe Packages
Ign http://old-releases.ubuntu.com lucid-updates/main Packages
Ign http://old-releases.ubuntu.com lucid-updates/universe Packages
Ign http://old-releases.ubuntu.com lucid-security/main Packages
Ign http://old-releases.ubuntu.com lucid-security/universe Packages
Ign http://old-releases.ubuntu.com lucid/main Packages
Ign http://old-releases.ubuntu.com lucid/universe Packages
Ign http://old-releases.ubuntu.com lucid-updates/main Packages
Ign http://old-releases.ubuntu.com lucid-updates/universe Packages
Ign http://old-releases.ubuntu.com lucid-security/main Packages
Ign http://old-releases.ubuntu.com lucid-security/universe Packages
Err http://old-releases.ubuntu.com lucid/main Packages
  404  Not Found
Err http://old-releases.ubuntu.com lucid/universe Packages
  404  Not Found
Err http://old-releases.ubuntu.com lucid-updates/main Packages
  404  Not Found
Err http://old-releases.ubuntu.com lucid-updates/universe Packages
  404  Not Found
Err http://old-releases.ubuntu.com lucid-security/main Packages
  404  Not Found
Err http://old-releases.ubuntu.com lucid-security/universe Packages
  404  Not Found
Fetched 47.5kB in 2s (18.0kB/s)
W: Failed to fetch http://old-releases.ubuntu.com/ubuntu/dists/lucid/main/binary-amd64/Packages.gz  404  Not Found

W: Failed to fetch http://old-releases.ubuntu.com/ubuntu/dists/lucid/universe/binary-amd64/Packages.gz  404  Not Found

W: Failed to fetch http://old-releases.ubuntu.com/ubuntu/dists/lucid-updates/main/binary-amd64/Packages.gz  404  Not Found

W: Failed to fetch http://old-releases.ubuntu.com/ubuntu/dists/lucid-updates/universe/binary-amd64/Packages.gz  404  Not Found

W: Failed to fetch http://old-releases.ubuntu.com/ubuntu/dists/lucid-security/main/binary-amd64/Packages.gz  404  Not Found

W: Failed to fetch http://old-releases.ubuntu.com/ubuntu/dists/lucid-security/universe/binary-amd64/Packages.gz  404  Not Found

E: Some index files failed to download, they have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y     ros-boxturtle-ros     && rm -rf /var/lib/apt/lists/*     && mkdir /var/lib/apt/lists/partial' returned a non-zero code: 100
```

**Comment by eisoku9618** [comment]
It's interesting.
I can successfully build the dockerfile inside my PC.

```bash
cd /tmp/
git clone https://github.com/eisoku9618/docker_images.git -b fix-for-eol-distro
docker build --tag=ros:boxturtle-ros-lucid --no-cache docker_images/ros/boxturtle/ubuntu/lucid/ros/.
```

<details>
  <summary>output log of docker build inside my PC</summary>

```
Sending build context to Docker daemon   5.12kB

Step 1/11 : FROM ubuntu:lucid
 ---> e21dbcc7c9de
Step 2/11 : RUN sed -i -e 's/archive/old-releases/g' /etc/apt/sources.list
 ---> Running in f06de938732f
Removing intermediate container f06de938732f
 ---> 75dccfbc841e
Step 3/11 : RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD19BAB3CBF125EA
 ---> Running in b584d3ec0bee
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /etc/apt/secring.gpg --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys AD19BAB3CBF125EA
[91mgpg: requesting key CBF125EA from hkp server keyserver.ubuntu.com
[0m[91mgpg: key CBF125EA: public key "ROS Snapshot builder <rosbuild@ros.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
[0mRemoving intermediate container b584d3ec0bee
 ---> 344304b93f10
Step 4/11 : RUN echo "deb http://snapshots.ros.org/boxturtle/final/ubuntu lucid main" > /etc/apt/sources.list.d/ros-latest.list
 ---> Running in 9264f1811c1b
Removing intermediate container 9264f1811c1b
 ---> d91ac2428538
Step 5/11 : RUN locale-gen en_US.UTF-8
 ---> Running in 0adbcccf082e
Generating locales...
  en_US.UTF-8... done
Generation complete.
Removing intermediate container 0adbcccf082e
 ---> 4f73d56108f0
Step 6/11 : ENV LANG en_US.UTF-8
 ---> Running in b7a4a3490cdd
Removing intermediate container b7a4a3490cdd
 ---> b1f927697404
Step 7/11 : ENV ROS_DISTRO boxturtle
 ---> Running in 5d2cd1b83515
Removing intermediate container 5d2cd1b83515
 ---> c7181f290ed5
Step 8/11 : RUN apt-get update && apt-get install -y     ros-boxturtle-ros     && rm -rf /var/lib/apt/lists/*     && mkdir /var/lib/apt/lists/partial
 ---> Running in 621b8269a376
Get:1 http://snapshots.ros.org lucid Release.gpg [630B]
Ign http://snapshots.ros.org/boxturtle/final/ubuntu/ lucid/main Translation-en_US
Get:2 http://snapshots.ros.org lucid Release [11.7kB]
Get:3 http://old-releases.ubuntu.com lucid Release.gpg [189B]
Ign http://old-releases.ubuntu.com/ubuntu/ lucid/main Translation-en_US
Ign http://old-releases.ubuntu.com/ubuntu/ lucid/universe Translation-en_US
Get:4 http://old-releases.ubuntu.com lucid-updates Release.gpg [198B]
Ign http://old-releases.ubuntu.com/ubuntu/ lucid-updates/main Translation-en_US
Ign http://old-releases.ubuntu.com/ubuntu/ lucid-updates/universe Translation-en_US
Get:5 http://old-releases.ubuntu.com lucid-security Release.gpg [198B]
Ign http://old-releases.ubuntu.com/ubuntu/ lucid-security/main Translation-en_US
Ign http://old-releases.ubuntu.com/ubuntu/ lucid-security/universe Translation-en_US
Get:6 http://snapshots.ros.org lucid/main Packages [35.2kB]
Get:7 http://old-releases.ubuntu.com lucid Release [57.2kB]
Get:8 http://old-releases.ubuntu.com lucid-updates Release [185kB]
Get:9 http://old-releases.ubuntu.com lucid-security Release [58.7kB]
Get:10 http://old-releases.ubuntu.com lucid/main Packages [1,383kB]
Get:11 http://old-releases.ubuntu.com lucid/universe Packages [5,430kB]
Get:12 http://old-releases.ubuntu.com lucid-updates/main Packages [811kB]
Get:13 http://old-releases.ubuntu.com lucid-updates/universe Packages [357kB]
Get:14 http://old-releases.ubuntu.com lucid-security/main Packages [627kB]
Get:15 http://old-releases.ubuntu.com lucid-security/universe Packages [221kB]
Fetched 9,178kB in 8s (1,136kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
The following extra packages will be installed:
  autoconf automake autotools-dev binutils blt bsdmainutils build-essential
```

</details>

How did you get the log output? In travis, I could not find any boxturtle test.
- https://travis-ci.org/osrf/docker_images/builds/544806577

**Comment by ruffsl** [comment]
> How did you get the log output? In travis, I could not find any boxturtle test.

I think it may be my hotel wifi, as I just tested the PR branch locally above, but when I test remotely on my workstation at work it seems to build. Ok then. BTW, could you link to the announcement for the snapshot public key bits, as I couldn't find it from any of the recent official announcements.

**Comment by mikaelarguedas** [comment]
> BTW, could you link to the announcement for the snapshot public key bits, as I couldn't find it from any of the recent official announcements.

It looks like the snapshot key in here matches the one documented on the [ROS wiki](http://wiki.ros.org/action/fullsearch/SnapshotRepository) and the [analog PR](https://github.com/osrf/docker_templates/pull/64) to the templates.

@ruffsl Is the plan to iterate on this + #269 ? or to iterate on #278 that includes both the key and repo changes?

**Comment by eisoku9618** [comment]
> could you link to the announcement for the snapshot public key bits

As @mikaelarguedas mentioned, I copied the public key bits from https://github.com/osrf/docker_templates/pull/64 .
I don't know where this key comes from.

**Comment by ruffsl** [comment]
@eisoku9618 , could you open a PR to update the docker_template repo for legacy image.

**Comment by mikaelarguedas** [comment]
> could you open a PR to update the docker_template repo for legacy image.

@ruffsl Would https://github.com/osrf/docker_templates/pull/64 be sufficient ?

**Pull request merged**
