### PR TITLE
bump kinetic version to 1.3.1

### PR DESCRIPTION
**Pull request by mikaelarguedas**
now the the kinetic sync happened we can update the docker image. Successfully built all of them locally

### CODE REVIEW

**Comment by ruffsl** [comment]
LGTM

By the way, do you think it would be better to swap the create_dockerfiles script for ros to scrape from the repo package index like gazebo does rather than the get_index function from rosdistro python lib. I never knew the apt repo and the rosdistro index would be out of sync for so long.

**Comment by mikaelarguedas** [comment]
We try to have syncs every two weeks but if there are regression it can take longer. I think it's a good feature to have (scraping from the repos rather than rosdistro) :+1: .

Hopefully pushing wrong version numbers should not happen again. We discussed it within the ROS team and the conclusion (https://github.com/ros/metapackages/issues/16#issuecomment-303518969) is that updating the images of a ROS distro should be the responsability of the ROS boss of that distro. So bumping the version number of a distro you are not responsible of should not happen in theory.
Furthermore these images should not have to be updated very often given that they need to change only when the metapackages change. Which is pretty/very rare

**Comment by ruffsl** [comment]
Ok, I'll work on a PR to enable the ros script to scrape from the repos.
Could you make the PR change to official library, thanks!

**Comment by mikaelarguedas** [comment]
> Ok, I'll work on a PR to enable the ros script to scrape from the repos.

Awesome thanks! ideally we could have an option to select the test (ros-shadow-fixed) or the main repo so that the "testing" image would stay in sync with rosdistro while the "stable" one would be updated every sync

Sure, I'll wait for @nkoenig response to https://github.com/osrf/docker_images/pull/56#issuecomment-307600477 to include gazebo7.8 in it or not. Thanks for reviewing!

**Comment by mikaelarguedas** [comment]
Given that the changes are not related and that one changes the way to find os version while this one is just bumping a version number I'm going to open a self contained PR only for this change and we will open another one for the gazebo changes and iterate on it if the new strategy to detect version is not good practice.

**Pull request merged**
