### PR TITLE
Add support for arm32v7 and arm64v8 with Gazebo v9

### PR DESCRIPTION
**Pull request by ruffsl**
Fixes: https://github.com/osrf/docker_images/issues/173

See available package listings:
* http://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/bionic/main/binary-amd64/Packages
* http://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/bionic/main/binary-armhf/Packages
* http://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/bionic/main/binary-arm64/Packages 
* http://packages.osrfoundation.org/gazebo/debian-stable/dists/stretch/main/binary-amd64/Packages
* http://packages.osrfoundation.org/gazebo/debian-stable/dists/stretch/main/binary-armhf/Packages
* http://packages.osrfoundation.org/gazebo/debian-stable/dists/stretch/main/binary-arm64/Packages

### CODE REVIEW

**Comment by ruffsl** [comment]
I figured I'd add images for debian to match what we support for our ROS images, and updated the template file to reflect this. @j-rivero , let me know if this addition seems sound.

**Comment by lag-linaro** [comment]
LGTM

**Comment by ruffsl** [comment]
Merging and letting CI generate a PR to bump the version.

**Comment by odidev** [comment]
Hi Guys,

```Gazebo``` at Docker-Hub still supports ```amd64``` architecture only.
It seems it needs a PR at https://github.com/docker-library/official-images/blob/master/library/gazebo to update the new list of architectures.

Regards,

**Comment by ruffsl** [comment]
@odidev , https://github.com/docker-library/official-images/pull/5096 is already staged.

**Comment by odidev** [comment]
Thanks, @ruffsl  for a quick update.

**Pull request merged**
