### PR TITLE
Adding Gazebo9 for xenial

### PR DESCRIPTION
**Pull request by ruffsl**
Fixes https://github.com/osrf/docker_images/issues/116

### CODE REVIEW

**Comment by ruffsl** [comment]
Let me know if 5c09518 is worth including.

**Comment by mikaelarguedas** [comment]
> Let me know if 5c09518 is worth including.

I don't think it's needed but it cannot hurt, especially for the not-EOL ones that are targetting multiple distros.
Regarding the EOL ones: Does it make sense to update and rebuild them ? (IDK if there has been discussion similar to https://github.com/osrf/docker_images/issues/79 for gazebo images)

**Comment by ruffsl** [comment]
> Regarding the EOL ones: Does it make sense to update and rebuild them ?

Those Dockerfiles have not changed, so the docker build farm should just add the tag to the catched images. However, if we modified all templates to include the [complete version](https://github.com/osrf/docker_images/issues/112#issuecomment-361806162), that would trigger a rebuild. Before that though, we could just comment them out from the manifest like we did with Jade to avoid that.

**Comment by mikaelarguedas** [comment]
> Those Dockerfiles have not changed, so the docker build farm should just add the tag to the catched images. 

I meant rebuilding them for each base image change.

> if we modified all templates to include the complete version, that would trigger a rebuild

Yeah I'm still not convinced this approach brings us much benefits compared to the one suggested by the docker maintainers. But let's keep this discussion separated for now.

> Before that though, we could just comment them out from the manifest like we did with Jade to avoid that.

:+1: yup, that sounds good to me (relevant PR for reference: #109), we should check with the gazebo team though.
If you prefer I can open a separate issue to discuss EOL gazebo images if that allows us to get this one merged in a timely manner

**Comment by ruffsl** [comment]
> I meant rebuilding them for each base image change.

I don't understand, none of the EOL gazebo tag are changing base images here. Do you mean when eventually bumping the plane `libgazebo` or `latest` tags when targeting the latest supported base LTS image when released?

> If you prefer I can open a separate issue to discuss EOL gazebo images if that allows us to get this one merged in a timely manner

Sounds good.

**Comment by mikaelarguedas** [comment]
> I don't understand, none of the EOL gazebo tag are changing base images here. Do you mean when eventually bumping the plane libgazebo or latest tags when targeting the latest supported base LTS image when released?

Sorry that was unclear: as ubuntu images are the lowest level base image for all gazebo images, they all get rebuilt when a new ubuntu image comes out, right ?

**Comment by mikaelarguedas** [comment]
@ruffsl opened #118 to track the EOL distros discussion

**Comment by ruffsl** [comment]
> as ubuntu images are the lowest level base image for all gazebo images, they all get rebuilt when a new ubuntu image comes out, right ?

Ah yes, true indeed. Though I suspect for official library image pipeline, cache breaks are fine grained to individual tag changes, rather than merely repo wide triggers as with automated docker hub user images. So (my guess), should amd64/ubuntu:xenial update, a build for arm32v7/ros:indigo would not be triggered due to it being dependant on a separate ubuntu tag and arch.

**Comment by ruffsl** [comment]
Just tried it out with gzweb, all seems to work fine.

**Pull request merged**
