### PR TITLE
EOL ROS2 Crystal

### PR DESCRIPTION
**Pull request by ruffsl**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Reminder that Crystal is not EOL yet and will likely see a sync or 2 before reaching end of life status

**Comment by ruffsl** [comment]
Yep, this is just a draft reminder for after the new year.

**Comment by mikaelarguedas** [comment]
Preempting PR to use the snapshots repos at https://github.com/osrf/docker_images/pull/343

**Comment by mikaelarguedas** [comment]
Crystal is now officially EOL https://github.com/ros/rosdistro/pull/23486

added https://github.com/osrf/docker_images/pull/338/commits/a47bcfb61ec846dd1d13d8d5e4a346b4c501c947 for completeness
didnt delete the hook scripts themselves as we kept them [for older distros](https://github.com/osrf/docker_images/blob/bd0d7f7d9f8cd0d89bea65531bee9e85a582227a/ros/indigo/ubuntu/trusty/desktop/hooks/post_push#L1). I can clean those up as well if preferred.

**Comment by ruffsl** [comment]
LGTM

**Comment by mikaelarguedas** [comment]
official images PR: https://github.com/docker-library/official-images/pull/7296

**Pull request merged**
