### PR TITLE
Move ros1-bridge images to the official docker library

### PR DESCRIPTION
**Pull request by mikaelarguedas**
This also deleted the hooks.

If / once merged we'll need to remove the triggers on dockerhub and to announce the shift on discourse.

Fixes https://github.com/osrf/docker_images/issues/414

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Here is the package list  difference (Extracted from existing images `ros:eloquent-ros-base` and `osrf/ros:eloquent-ros1-bridge`)

The only one that doesn't seem right is the removal of `python3-rosdep` without reinstalling `python-rosdep` to replace it. That means the rosdep cli is not usable so I'm keen on adding that back.
For the other ones their Python2 counterpart is being installed instead so the CLI will still work, so it should be fine.


<details><summary>Packages removed compared to ros-base image</summary>
```
python3-catkin-pkg
python3-rosdep
python3-rosdep-modules
python3-rosdistro
python3-rospkg
```
</details>

<details><summary>Packages added compared to ros-base image</summary>

```
gir1.2-glib-2.0
gir1.2-harfbuzz-0.0
ibverbs-providers
icu-devtools
libapr1
libapr1-dev
libaprutil1
libaprutil1-dev
libassuan-dev
libboost-all-dev
libboost-atomic-dev
libboost-atomic1.65-dev
libboost-atomic1.65.1
libboost-chrono-dev
libboost-chrono1.65-dev
libboost-chrono1.65.1
libboost-container-dev
libboost-container1.65-dev
libboost-container1.65.1
libboost-context-dev
libboost-context1.65-dev
libboost-context1.65.1
libboost-coroutine-dev
libboost-coroutine1.65-dev
libboost-coroutine1.65.1
libboost-date-time-dev
libboost-date-time1.65-dev
libboost-date-time1.65.1
libboost-dev
libboost-exception-dev
libboost-exception1.65-dev
libboost-fiber-dev
libboost-fiber1.65-dev
libboost-fiber1.65.1
libboost-filesystem-dev
libboost-filesystem1.65-dev
libboost-filesystem1.65.1
libboost-graph-dev
libboost-graph-parallel-dev
libboost-graph-parallel1.65-dev
libboost-graph-parallel1.65.1
libboost-graph1.65-dev
libboost-graph1.65.1
libboost-iostreams-dev
libboost-iostreams1.65-dev
libboost-iostreams1.65.1
libboost-locale-dev
libboost-locale1.65-dev
libboost-locale1.65.1
libboost-log-dev
libboost-log1.65-dev
libboost-log1.65.1
libboost-math-dev
libboost-math1.65-dev
libboost-math1.65.1
libboost-mpi-dev
libboost-mpi-python-dev
libboost-mpi-python1.65-dev
libboost-mpi-python1.65.1
libboost-mpi1.65-dev
libboost-mpi1.65.1
libboost-numpy-dev
libboost-numpy1.65-dev
libboost-numpy1.65.1
libboost-program-options-dev
libboost-program-options1.65-dev
libboost-program-options1.65.1
libboost-python-dev
libboost-python1.65-dev
libboost-python1.65.1
libboost-random-dev
libboost-random1.65-dev
libboost-random1.65.1
libboost-regex-dev
libboost-regex1.65-dev
libboost-regex1.65.1
libboost-serialization-dev
libboost-serialization1.65-dev
libboost-serialization1.65.1
libboost-signals-dev
libboost-signals1.65-dev
libboost-signals1.65.1
libboost-stacktrace-dev
libboost-stacktrace1.65-dev
libboost-stacktrace1.65.1
libboost-system-dev
libboost-system1.65-dev
libboost-system1.65.1
libboost-test-dev
libboost-test1.65-dev
libboost-test1.65.1
libboost-thread-dev
libboost-thread1.65-dev
libboost-thread1.65.1
libboost-timer-dev
libboost-timer1.65-dev
libboost-timer1.65.1
libboost-tools-dev
libboost-type-erasure-dev
libboost-type-erasure1.65-dev
libboost-type-erasure1.65.1
libboost-wave-dev
libboost-wave1.65-dev
libboost-wave1.65.1
libboost1.65-dev
libboost1.65-tools-dev
libbz2-dev
libelf1
libfabric1
libfreetype6
libgirepository-1.0-1
libglib2.0-bin
libglib2.0-data
libglib2.0-dev
libglib2.0-dev-bin
libgpg-error-dev
libgpgme-dev
libgpgme11
libgraphite2-3
libgraphite2-dev
libharfbuzz-dev
libharfbuzz-gobject0
libharfbuzz-icu0
libharfbuzz0b
libhwloc-dev
libhwloc-plugins
libhwloc5
libibverbs-dev
libibverbs1
libicu-dev
libicu-le-hb-dev
libicu-le-hb0
libiculx60
libldap2-dev
liblog4cxx-dev
liblog4cxx10v5
libltdl-dev
liblz4-dev
libnl-3-200
libnl-route-3-200
libnuma-dev
libnuma1
libopenmpi-dev
libopenmpi2
libpciaccess0
libpng16-16
libpsm-infinipath1
libpython-dev
libpython2.7
libpython2.7-dev
librdmacm1
libsctp-dev
libsctp1
mpi-default-bin
mpi-default-dev
ocl-icd-libopencl1
openmpi-bin
openmpi-common
python-asn1crypto
python-catkin-pkg
python-catkin-pkg-modules
python-cffi-backend
python-cryptography
python-dateutil
python-defusedxml
python-dev
python-docutils
python-empy
python-enum34
python-gnupg
python-idna
python-ipaddress
python-netifaces
python-nose
python-numpy
python-paramiko
python-pyasn1
python-pycryptodome
python-pyparsing
python-roman
python-rosdep-modules
python-rosdistro
python-rosdistro-modules
python-rospkg
python-rospkg-modules
python-setuptools
python-yaml
python2.7-dev
ros-eloquent-demo-nodes-cpp
ros-eloquent-demo-nodes-py
ros-eloquent-example-interfaces
ros-eloquent-gazebo-msgs
ros-eloquent-ros1-bridge
ros-melodic-actionlib-msgs
ros-melodic-catkin
ros-melodic-class-loader
ros-melodic-common-msgs
ros-melodic-cpp-common
ros-melodic-diagnostic-msgs
ros-melodic-gazebo-msgs
ros-melodic-gencpp
ros-melodic-geneus
ros-melodic-genlisp
ros-melodic-genmsg
ros-melodic-gennodejs
ros-melodic-genpy
ros-melodic-geometry-msgs
ros-melodic-message-filters
ros-melodic-message-generation
ros-melodic-message-runtime
ros-melodic-mk
ros-melodic-nav-msgs
ros-melodic-pluginlib
ros-melodic-ros
ros-melodic-ros-comm
ros-melodic-ros-environment
ros-melodic-rosbag
ros-melodic-rosbag-migration-rule
ros-melodic-rosbag-storage
ros-melodic-rosbash
ros-melodic-rosboost-cfg
ros-melodic-rosbuild
ros-melodic-rosclean
ros-melodic-rosconsole
ros-melodic-roscpp
ros-melodic-roscpp-serialization
ros-melodic-roscpp-traits
ros-melodic-roscpp-tutorials
ros-melodic-roscreate
ros-melodic-rosgraph
ros-melodic-rosgraph-msgs
ros-melodic-roslang
ros-melodic-roslaunch
ros-melodic-roslib
ros-melodic-roslisp
ros-melodic-roslz4
ros-melodic-rosmake
ros-melodic-rosmaster
ros-melodic-rosmsg
ros-melodic-rosnode
ros-melodic-rosout
ros-melodic-rospack
ros-melodic-rosparam
ros-melodic-rospy
ros-melodic-rospy-tutorials
ros-melodic-rosservice
ros-melodic-rostest
ros-melodic-rostime
ros-melodic-rostopic
ros-melodic-rosunit
ros-melodic-roswtf
ros-melodic-sensor-msgs
ros-melodic-shape-msgs
ros-melodic-std-msgs
ros-melodic-std-srvs
ros-melodic-stereo-msgs
ros-melodic-tf2-msgs
ros-melodic-topic-tools
ros-melodic-trajectory-msgs
ros-melodic-visualization-msgs
ros-melodic-xmlrpcpp
sbcl
uuid-dev
```

</details>

**Comment by ruffsl** [comment]
Do we still want to install the ros1 tutorial and ros2 demo packages? Although they give a quick means to test the bridge container with itself, those packages are not necessary dependencies for the `ros1-bridge` package. How much space would be saved if we skipped those?

https://github.com/osrf/docker_images/blob/1c9b345c196d3c614039a8fa95a323a500175b7a/ros/eloquent/ubuntu/bionic/ros1-bridge/Dockerfile#L21-L25

I forget, did we have a good reason to unset the helper envs?
They might be handy to check what distros are configured at runtime.

https://github.com/osrf/docker_images/blob/1c9b345c196d3c614039a8fa95a323a500175b7a/ros/eloquent/ubuntu/bionic/ros1-bridge/ros_entrypoint.sh#L14-L15

> Packages removed compared to ros-base image

Do those conflict with ros1 packages an any meaningful way?
Could they be kept and supersede the python2 versions?
Or would it just not be worth sorting out.

> Packages added compared to ros-base image

I'm guessing this may be a bit shorter with foxy/noetic, with pruning of boost and python3 switch?

**Comment by ruffsl** [comment]
Do you think it might be helpful to change the default `CMD` to launch the rosbridge? I'm kind of partial to keeping it `bash` like all the other tags. If `bash`, then this line is redundent and can be removed.

https://github.com/osrf/docker_images/blob/1c9b345c196d3c614039a8fa95a323a500175b7a/ros/eloquent/ubuntu/bionic/ros1-bridge/Dockerfile#L30-L31

**Comment by ruffsl** [comment]
Also, is `ros_comm` the package we'd want to go with in terms of ros1 dependencies?

https://github.com/osrf/docker_images/blob/1c9b345c196d3c614039a8fa95a323a500175b7a/ros/eloquent/ubuntu/bionic/ros1-bridge/Dockerfile#L15

Would we want to use a meta-package like `ros_core` that includes things like `std_msgs`, `std_srvs` and `common_msgs`?

https://www.ros.org/reps/rep-0150.html#metapackages

**Comment by ruffsl** [comment]
See potential patch for this PR here: https://github.com/osrf/docker_images/pull/416

**Comment by mikaelarguedas** [comment]
> Do we still want to install the ros1 tutorial and ros2 demo packages? Although they give a quick means to test the bridge container with itself, those packages are not necessary dependencies for the ros1-bridge package. How much space would be saved if we skipped those?

Unfortunately they are. At lease the ROS 1 ones as they provide some service definitions used to compile the bridge: https://github.com/ros2/ros1_bridge/issues/228

The ROS 2 demo packages were added for consistency and simpler testing. The space that would be saved removing them is pretty small
```
The following packages will be REMOVED:
  ros-eloquent-demo-nodes-cpp ros-eloquent-demo-nodes-py
0 upgraded, 0 newly installed, 2 to remove and 91 not upgraded.
After this operation, 2284 kB disk space will be freed.
```

>  forget, did we have a good reason to unset the helper envs?
They might be handy to check what distros are configured at runtime.

I believe it was just to limit our environment footprint as these variables have nothing official (we made them up to simplify our sourcing).

> They might be handy to check what distros are configured at runtime.

I guess we could keep them, it wouldnt cost anything to do it.
There is no direct way to retrieve which underlay distro has been sourced indeed. Although the environment will contain this information in a more indirect way as ROS1 and ROS 2 set some env vars that are not the same (AMENT_PREFIX_PATH, ROS_PACKAGE_PATH etc).

>  Could they be kept and supersede the python2 versions?

The image is based on the ros-base image, these were removed because they were conflicting with the ROS1 install so reinstalling them would remove the ROS 1 packages.

> I'm guessing this may be a bit shorter with foxy/noetic, with pruning of boost and python3 switch?

A bit though not significantly because despite effort theres still a lost of libboost-all in ROS 1 packages.

> Would we want to use a meta-package like ros_core that includes things like std_msgs, std_srvs and common_msgs?

`ros_comm` is a metapackage. The `ros1_bridge` already depends on all the common messages (and provides mapping for them). `ros_comm` is used to have tools like `roslaunch` and `rosrun` that are not dependencies od the ros1-bridge package. I don't think there is a need or a will to install all ros_core, could you provide the list of which additional packages it would bring ?

**Comment by ruffsl** [comment]
> Unfortunately they are. At lease the ROS 1 ones as they provide some service definitions used to compile the bridge: ros2/ros1_bridge#228

Ok, that is unfortunate but see why now. We'll keep the demos installed then.

> I guess we could keep them, it wouldnt cost anything to do it.

I've updated the endpoint to let them be, as well removed the redundant Dockerfile derectives.

**Comment by mikaelarguedas** [comment]
I made an attempt to install back the rosdep-modules but it failed because they are currently not side by side installable https://github.com/ros-infrastructure/rosdep/issues/759

So it installs only `python-rosdep` back to have a working rosdep install in the image.

It needed https://github.com/osrf/docker_templates/pull/88 to be able to do so

**Comment by ruffsl** [comment]
> So it installs only python-rosdep back to have a working rosdep install in the image.

Dang. Although, this should be a non issue for foxy/noetic given the complete move to python3?

**Comment by mikaelarguedas** [comment]
> Dang. Although, this should be a non issue for foxy/noetic given the complete move to python3?

Yes that's my expectation

**Comment by mikaelarguedas** [comment]
> > I'm guessing this may be a bit shorter with foxy/noetic, with pruning of boost and python3 switch?

> A bit though not significantly because despite effort theres still a lost of libboost-all in ROS 1 packages.

I confirmed that the foxy ROS 1 bridge does bring in all boost libraries, main culprits seem to be actionlib, tf and tf2-ros. It seems that we could remove the need for all these dependencies if the bridge doesnt build with support for tf1 messages (deprecated for many years now) https://github.com/ros2-gbp/ros1_bridge-release/pull/11.

<details><summary>That would save the installation of ~380MB of stuff</summary>

```
The following additional packages will be installed:
  autoconf automake autotools-dev cpp-8 fontconfig fontconfig-config fonts-dejavu-core fonts-liberation gcc-8 gfortran gfortran-8 gfortran-9 graphviz ibverbs-providers libann0 libboost-all-dev
  libboost-atomic-dev libboost-container-dev libboost-container1.71-dev libboost-container1.71.0 libboost-context-dev libboost-context1.71-dev libboost-context1.71.0 libboost-coroutine-dev
  libboost-coroutine1.71-dev libboost-coroutine1.71.0 libboost-exception-dev libboost-exception1.71-dev libboost-fiber-dev libboost-fiber1.71-dev libboost-fiber1.71.0 libboost-graph-dev
  libboost-graph-parallel-dev libboost-graph-parallel1.71-dev libboost-graph-parallel1.71.0 libboost-graph1.71-dev libboost-graph1.71.0 libboost-iostreams-dev libboost-iostreams1.71-dev
  libboost-iostreams1.71.0 libboost-locale-dev libboost-locale1.71-dev libboost-locale1.71.0 libboost-log-dev libboost-log1.71-dev libboost-log1.71.0 libboost-math-dev libboost-math1.71-dev libboost-math1.71.0
  libboost-mpi-dev libboost-mpi-python-dev libboost-mpi-python1.71-dev libboost-mpi-python1.71.0 libboost-mpi1.71-dev libboost-mpi1.71.0 libboost-numpy-dev libboost-numpy1.71-dev libboost-numpy1.71.0
  libboost-python-dev libboost-python1.71-dev libboost-python1.71.0 libboost-random-dev libboost-random1.71-dev libboost-random1.71.0 libboost-serialization-dev libboost-stacktrace-dev
  libboost-stacktrace1.71-dev libboost-stacktrace1.71.0 libboost-test-dev libboost-test1.71-dev libboost-test1.71.0 libboost-timer-dev libboost-timer1.71-dev libboost-timer1.71.0 libboost-tools-dev
  libboost-type-erasure-dev libboost-type-erasure1.71-dev libboost-type-erasure1.71.0 libboost-wave-dev libboost-wave1.71-dev libboost-wave1.71.0 libboost1.71-tools-dev libbsd0 libcaf-openmpi-3 libcairo2
  libcbor0.6 libcdt5 libcgraph6 libcoarrays-dev libcoarrays-openmpi-dev libdatrie1 libedit2 libevent-2.1-7 libevent-core-2.1-7 libevent-dev libevent-extra-2.1-7 libevent-openssl-2.1-7 libevent-pthreads-2.1-7
  libfabric1 libfido2-1 libfontconfig1 libfreetype6 libfribidi0 libgcc-8-dev libgd3 libgfortran-8-dev libgfortran-9-dev libgraphite2-3 libgts-0.7-5 libgts-bin libgvc6 libgvpr2 libharfbuzz0b libhwloc-dev
  libhwloc-plugins libhwloc15 libibverbs-dev libibverbs1 libice6 libjbig0 libjpeg-turbo8 libjpeg8 liblab-gamut1 libltdl-dev libnl-3-200 libnl-3-dev libnl-route-3-200 libnl-route-3-dev libnuma-dev libnuma1
  libopenmpi-dev libopenmpi3 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpathplan4 libpciaccess0 libpixman-1-0 libpmix2 libpng16-16 libpsm-infinipath1 libpsm2-2 librdmacm1 libsigsegv2 libsm6
  libthai-data libthai0 libtiff5 libtool libwebp6 libx11-6 libx11-data libxau6 libxaw7 libxcb-render0 libxcb-shm0 libxcb1 libxdmcp6 libxext6 libxmu6 libxmuu1 libxnvctrl0 libxpm4 libxrender1 libxt6 m4
  mpi-default-bin mpi-default-dev ocl-icd-libopencl1 openmpi-bin openmpi-common openssh-client ros-noetic-actionlib ros-noetic-tf ros-noetic-tf2 ros-noetic-tf2-py ros-noetic-tf2-ros ucf x11-common xauth
Suggested packages:
  autoconf-archive gnu-standards autoconf-doc gettext gcc-8-locales gcc-8-multilib gcc-8-doc gfortran-multilib gfortran-doc gfortran-8-multilib gfortran-8-doc gfortran-9-multilib gfortran-9-doc gsfonts
  graphviz-doc libboost1.71-doc gccxml xsltproc doxygen docbook-xml docbook-xsl default-jdk fop libgd-tools libhwloc-contrib-plugins libtool-doc openmpi-doc pciutils gcj-jdk m4-doc opencl-icd keychain
  libpam-ssh monkeysphere ssh-askpass
The following NEW packages will be installed:
  autoconf automake autotools-dev cpp-8 fontconfig fontconfig-config fonts-dejavu-core fonts-liberation gcc-8 gfortran gfortran-8 gfortran-9 graphviz ibverbs-providers libann0 libboost-all-dev
  libboost-atomic-dev libboost-container-dev libboost-container1.71-dev libboost-container1.71.0 libboost-context-dev libboost-context1.71-dev libboost-context1.71.0 libboost-coroutine-dev
  libboost-coroutine1.71-dev libboost-coroutine1.71.0 libboost-exception-dev libboost-exception1.71-dev libboost-fiber-dev libboost-fiber1.71-dev libboost-fiber1.71.0 libboost-graph-dev
  libboost-graph-parallel-dev libboost-graph-parallel1.71-dev libboost-graph-parallel1.71.0 libboost-graph1.71-dev libboost-graph1.71.0 libboost-iostreams-dev libboost-iostreams1.71-dev
  libboost-iostreams1.71.0 libboost-locale-dev libboost-locale1.71-dev libboost-locale1.71.0 libboost-log-dev libboost-log1.71-dev libboost-log1.71.0 libboost-math-dev libboost-math1.71-dev libboost-math1.71.0
  libboost-mpi-dev libboost-mpi-python-dev libboost-mpi-python1.71-dev libboost-mpi-python1.71.0 libboost-mpi1.71-dev libboost-mpi1.71.0 libboost-numpy-dev libboost-numpy1.71-dev libboost-numpy1.71.0
  libboost-python-dev libboost-python1.71-dev libboost-python1.71.0 libboost-random-dev libboost-random1.71-dev libboost-random1.71.0 libboost-serialization-dev libboost-stacktrace-dev
  libboost-stacktrace1.71-dev libboost-stacktrace1.71.0 libboost-test-dev libboost-test1.71-dev libboost-test1.71.0 libboost-timer-dev libboost-timer1.71-dev libboost-timer1.71.0 libboost-tools-dev
  libboost-type-erasure-dev libboost-type-erasure1.71-dev libboost-type-erasure1.71.0 libboost-wave-dev libboost-wave1.71-dev libboost-wave1.71.0 libboost1.71-tools-dev libbsd0 libcaf-openmpi-3 libcairo2
  libcbor0.6 libcdt5 libcgraph6 libcoarrays-dev libcoarrays-openmpi-dev libdatrie1 libedit2 libevent-2.1-7 libevent-core-2.1-7 libevent-dev libevent-extra-2.1-7 libevent-openssl-2.1-7 libevent-pthreads-2.1-7
  libfabric1 libfido2-1 libfontconfig1 libfreetype6 libfribidi0 libgcc-8-dev libgd3 libgfortran-8-dev libgfortran-9-dev libgraphite2-3 libgts-0.7-5 libgts-bin libgvc6 libgvpr2 libharfbuzz0b libhwloc-dev
  libhwloc-plugins libhwloc15 libibverbs-dev libibverbs1 libice6 libjbig0 libjpeg-turbo8 libjpeg8 liblab-gamut1 libltdl-dev libnl-3-200 libnl-3-dev libnl-route-3-200 libnl-route-3-dev libnuma-dev libnuma1
  libopenmpi-dev libopenmpi3 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpathplan4 libpciaccess0 libpixman-1-0 libpmix2 libpng16-16 libpsm-infinipath1 libpsm2-2 librdmacm1 libsigsegv2 libsm6
  libthai-data libthai0 libtiff5 libtool libwebp6 libx11-6 libx11-data libxau6 libxaw7 libxcb-render0 libxcb-shm0 libxcb1 libxdmcp6 libxext6 libxmu6 libxmuu1 libxnvctrl0 libxpm4 libxrender1 libxt6 m4
  mpi-default-bin mpi-default-dev ocl-icd-libopencl1 openmpi-bin openmpi-common openssh-client ros-foxy-ros1-bridge ros-noetic-actionlib ros-noetic-tf ros-noetic-tf2 ros-noetic-tf2-py ros-noetic-tf2-ros ucf
  x11-common xauth
0 upgraded, 181 newly installed, 0 to remove and 0 not upgraded.
Need to get 75.5 MB of archives.
After this operation, 380 MB of additional disk space will be used.
```

</details>

**Comment by mikaelarguedas** [comment]
shipping these now to get the Foxy official ros1-bridge image for the announcement

**Pull request merged**
