### PR TITLE
[ros2:devel / ros2:nightly] install colcon from pip and not apt

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Related to https://github.com/ros2/ros2/issues/722

Fixes https://github.com/osrf/docker_images/issues/270

### CODE REVIEW

**Comment by ruffsl** [comment]
Would this PR be reverted once the packaging issue with `pytest` is resolved? I recall we previously migrated away from installing colcon from pip to apt for downstream consistency of dev tools.

Related: https://github.com/pytest-dev/pytest/pull/5389

**Comment by mikaelarguedas** [comment]
> Would this PR be reverted once the packaging issue with pytest is resolved?

Originally the goal is to install all the third-party tools from APT and not pip to allow conflict tracking and automatic upgrade.
In this particular case, I'm not convinced it needs to be reverted.
As this PR targets only the images that are expected to be built daily it shouldn't be too big of a deal to install colcon from pip. It also allows to move away from the error prone pattern of installing some pytest plugins from pip and the others from APT.
I doubt the fix will ever make it to bionic so we will need to install pytest via pip to get it.

**Comment by ruffsl** [comment]
> I doubt the fix will ever make it to bionic so we will need to install pytest via pip to get it.

Ah, that would do it.
Does this mean that `library/ros:dashing` images are left with a broken build tool?

**Comment by mikaelarguedas** [comment]
> Does this mean that library/ros:dashing images are left with a broken build tool?

No they should be fine as they dont install any plugins from pip. They just are not able to leverage the various pytest options that colcon provides (I think, I haven't built or tried the dashing images)

**Pull request merged**
